Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.debug import default_urlconf

urlpatterns = [
    url(r'^$', default_urlconf),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^property/', include('property.urls', namespace="property")),
    url(r'^user_access/', include('user_access.urls', namespace="user_access")),
    url(r'^submittal/', include('submittal.urls', namespace="submittal")),
    url(r'^submittal_employees/', include('submittal_employees.urls', namespace="submittal_employees")),
]

property/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^property_test/$', views.PropertyTest, name='property_test'),
    url(r'^(?P<property_id>[0-9]+)/$', views.PropertyDetail, name='property_detail'),
    url(r'^', views.PropertyIndex, name='index'),
]

submittal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<submittal_id>[0-9]+)/edit_yes_no/(?P<yes_no_type>\w+)/$', views.EditYesNo, name='edit_yes_no'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_quantity/(?P<quantity_input_type>\w+)/$', views.EditQuantityAmount, name='edit_quantity_amount'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_amount/(?P<dollar_input_type>\w+)/$', views.EditDollarAmount, name='edit_dollar_amount'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_rate/(?P<rate_type>\w+)/$', views.EditRate, name='edit_rate'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_opening_date/$', views.EditOpeningDate, name='edit_opening_date'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_stabilization_date/$', views.EditStabilizationDate, name='edit_stabilization_date'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_leasing_status/$', views.EditLeasingStatus, name='edit_leasing_status'),
    url(r'^(?P<submittal_id>[0-9]+)/$', views.SubmittalDetail, name='submittal_detail')
]

submittal/models.py
from __future__ import unicode_literals
from property.models import Property
from django.db import models

class Submittal(models.Model):
    prop = models.ForeignKey(Property)
    submittal_year = models.IntegerField(default=0)
    submittal_month = models.IntegerField(default=0)
    #boolean 0/1 field; 0 is not submitted and 1 is submitted
    #indicates whether or not the property manager has completed the form and submitted the bonus
    pm_submitted = models.IntegerField(default=0)
    #boolean 0/1 field; 0 is not approved yet and 1 is approved
    #indicates whether the RM has approved the bonus after having reviewed it
    rm_approved = models.IntegerField(default=0)
    #boolean 0/1 field; 0 is not approved yet and 1 is approved
    #indicates whether the bonus has been submitted to payroll for processing after RM approval
    #in typical usage, should automatically be marked as submitted once the scheduled submittal process runs
    payroll_submitted = models.IntegerField(default=0)
    occupancy_rate = models.DecimalField(max_digits=4,decimal_places=1, null=True)
    #options are leaseup and stabilized
    #pre_leasing for the application bonus will be determined based on applications submitted prior to the date
    #of the first move-in
    leasing_status = models.CharField(max_length=20, null=True)
    op_rev_month_budget = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    op_rev_month_actual = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    noi_semi_ann_budget = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    noi_semi_ann_actual = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    op_rev_qtr_budget = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    op_rev_qtr_actual = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    #boolean 0/1 field; 0 is no override bonus and 1 is that that bonus is approved
    lease_up_override = models.IntegerField(default=0)
    delinquency_rate = models.DecimalField(max_digits=4, decimal_places=1, null=True)
    #boolean 0/1 field; 0 is that there were no bad debt write-offs and 1 is that there were
    bad_debt_writeoffs = models.IntegerField(default=0)
    #this is a check to confirm whether all necessary information for the submittal has been entered
    #before allowing the user to calculate specific bonus amounts
    #0/1 boolean with 0 not submitted and 1 is fully submitted
    #will be used as a toggle in the view to allow specific bonus amounts to be calculated
    data_complete = models.IntegerField(default=0)

submittal/forms.py
from django import forms


class EditLeasingStatusForm(forms.Form):
    def __init__(self,
                 leasing_status_choices,
                 *args,
                 **kwargs):
        super(EditLeasingStatusForm, self).__init__(*args, **kwargs)
        self.fields['leasing_status'].choices = leasing_status_choices

    leasing_status = forms.ChoiceField(
        choices=(),
        required=True,
        label='Leasing Status'
    )


class EnterStabilizationDateForm(forms.Form):
    def __init__(self,
                 year_choices,
                 month_choices,
                 day_choices,
                 *args,
                 **kwargs):
        super(EnterStabilizationDateForm, self).__init__(*args, **kwargs)
        self.fields['stabilization_year'].choices = year_choices
        self.fields['stabilization_month'].choices = month_choices
        self.fields['stabilization_day'].choices = day_choices

    stabilization_year = forms.ChoiceField(
        choices=(),
        required=True,
        label='Year'
    )
    stabilization_month = forms.ChoiceField(
        choices=(),
        required=True,
        label='Month'
    )
    stabilization_day = forms.ChoiceField(
        choices=(),
        required=True,
        label='Day'
    )


class EnterOpeningDateForm(forms.Form):
    def __init__(self,
                 year_choices,
                 month_choices,
                 day_choices,
                 *args,
                 **kwargs):
        super(EnterOpeningDateForm, self).__init__(*args, **kwargs)
        self.fields['opening_year'].choices = year_choices
        self.fields['opening_month'].choices = month_choices
        self.fields['opening_day'].choices = day_choices

    opening_year = forms.ChoiceField(
        choices=(),
        required=True,
        label='Year'
    )
    opening_month = forms.ChoiceField(
        choices=(),
        required=True,
        label='Month'
    )
    opening_day = forms.ChoiceField(
        choices=(),
        required=True,
        label='Day'
    )


#use this form to edit any input that requires a percentage between 0% - 100%
class EditRateForm(forms.Form):
    def __init__(self,
                 rate_choices,
                 *args,
                 **kwargs):
        super(EditRateForm, self).__init__(*args, **kwargs)
        self.fields['rate_amount'].choices = rate_choices

    rate_amount = forms.DecimalField(max_digits=4, decimal_places=1, max_value=100.0, min_value=0, required=True, label='% Rate')

#use this form to edit any input that requires a dollar amount
class EditDollarInputForm(forms.Form):
    dollar_amount = forms.DecimalField(max_digits=12, decimal_places=2, min_value=0, required=True, label='$ Amount')

#use this form to edit any input that requires a quantity to be entered, such as the number of bad debt write-offs
class EditQuantityForm(forms.Form):
    quantity_amt = forms.IntegerField(min_value=0, required=True, label='# Quantity')

#use this form to edit any input that requires a yes/no response
class EditYesNoForm(forms.Form):
    def __init__(self,
                 yes_no_choices,
                 *args,
                 **kwargs):
        super(EditYesNoForm, self).__init__(*args, **kwargs)
        self.fields['yes_no_select'].choices = yes_no_choices

    yes_no_select = forms.ChoiceField(
        choices=(),
        required=True,
        label='Yes/No'
    )

submittal/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from property.models import Property
from submittal_employees.models import Submittal_Employees
from employees.models import Employees
from .models import Submittal
from .forms import EditLeasingStatusForm, EnterStabilizationDateForm, EnterOpeningDateForm, EditRateForm, EditDollarInputForm, EditQuantityForm, EditYesNoForm
from user_access.tools import CheckAuthorization
import datetime

@login_required
def SubmittalDetail(request, submittal_id):
    submittal = Submittal.objects.get(id=submittal_id)
    property_id = submittal.prop_id
    property = Property.objects.get(id=property_id)
    #check that the logged-in user is authorized to view the property
    authorized_user = CheckAuthorization(request, property_id)
    if authorized_user == True:
        #check the submittal status to see whether or not the user can edit the numbers
        submittal_status = CheckSubmissionStatus(submittal_id=submittal_id)
        #check that the property has enetered an opening date
        open_date_complete = CheckOpeningDate(property_id=property_id)
        #check that a stabilization date has been entered if the property is listed as stabilized
        stabilization_date_complete = CheckStabilizationDate(submittal_id=submittal_id)
        #convert the boolean 0/1 for lease-up override to 'yes' or 'no'
        lease_up_override = 'No'
        if submittal.lease_up_override == 1:
            lease_up_override = 'Yes'
        #convert the boolean 0/1 for bad debt writeoff to 'yes' or 'no'
        bad_debt_writeoff = 'No'
        if submittal.bad_debt_writeoffs == 1:
            bad_debt_writeoff = 'Yes'
        #check that the leasing status has been filled out
        leasing_status_confirmed = 'No'
        if submittal.leasing_status == 'stabilized' or submittal.leasing_status == 'leaseup':
            leasing_status_confirmed = 'Yes'
        #check whether or not all of the open data points has been filled out to allow for bonuses to be calculated
        data_points_complete = CheckDataPoints(submittal_id=submittal_id)
        if data_points_complete == 'complete' and submittal.data_complete == 0:
            submittal.data_complete = 1
            submittal.save()
        if data_points_complete == 'incomplete' and submittal.data_complete == 1:
            submittal.data_complete = 0
            submittal.save()
        #check whether or not it is a fiscal half end
        fiscal_halfs = ConvertFiscalHalfs(property.fiscal_start)
        half_1 = fiscal_halfs['half_1']
        half_2 = fiscal_halfs['half_2']
        fiscal_qtrs = ConvertFiscalQuarters(property.fiscal_start)
        qtr_1 = fiscal_qtrs['qtr_1']
        qtr_2 = fiscal_qtrs['qtr_2']
        qtr_3 = fiscal_qtrs['qtr_3']
        qtr_4 = fiscal_qtrs['qtr_4']
        fiscal_half_end = 'No'
        fiscal_qtr_end = 'No'
        checkleaseupfiscalhalf = CheckFiscalHalfLeaseup(property_id=property_id)
        if submittal.leasing_status == 'stabilized':
            if submittal.submittal_month == half_1 or submittal.submittal_month == half_2:
                fiscal_half_end = 'Yes'
                if checkleaseupfiscalhalf == True:
                    fiscal_qtr_end = 'Yes'
        if submittal.leasing_status == 'leaseup':
            if submittal.submittal_month == qtr_1 or submittal.submittal_month == qtr_2 or submittal.submittal_month == qtr_3 or submittal.submittal_month == qtr_4:
                fiscal_qtr_end = 'Yes'
        employees = SubmittalEmployees(submittal_id=submittal_id)
        context = {'submittal': submittal,
                   'property': property,
                   'lease_up_override': lease_up_override,
                   'bad_debt_writeoff': bad_debt_writeoff,
                   'leasing_status_confirmed': leasing_status_confirmed,
                   'submittal_status': submittal_status,
                   'open_date_complete': open_date_complete,
                   'stabilization_date_complete': stabilization_date_complete,
                   'data_points_complete': data_points_complete,
                   'fiscal_half_end': fiscal_half_end,
                   'fiscal_qtr_end': fiscal_qtr_end,
                   'employees': employees,
                   }
        return render(request, 'submittal/submittal_detail.html', context)

@login_required
def EditLeasingStatus(request, submittal_id):
    submittal = Submittal.objects.get(id=submittal_id)
    property_id = submittal.prop_id
    property = Property.objects.get(id=property_id)
    options = LeasingStatusOptions()
    input_form_title = 'Edit Leasing Status'
    #check that the user is authorized
    authorized_user = CheckAuthorization(request, property_id)
    if authorized_user == True:
        if request.method == 'POST':
            form = EditLeasingStatusForm(
                data=request.POST,
                leasing_status_choices=options,
            )
            if form.is_valid():
                data = form.cleaned_data
                #check to make sure that they are not changing status from stabilized to leaseup
                prior_period = PriorMonthSubmittalDates(submittal_id=submittal_id)
                prior_year = prior_period['prior_year']
                prior_month = prior_period['prior_month']
                submittal_prior_month = Submittal.objects.filter(prop_id=property_id,
                                                                 submittal_year=prior_year,
                                                                 submittal_month=prior_month)
                leasing_status_prior_month = None
                leasing_status_current_month = data['leasing_status']
                #if the queryset for the prior month submittal comes back empty, it means there wasn't a submittal
                #and that any leasing status now submitted can be saved
                if not submittal_prior_month:
                    submittal.leasing_status = leasing_status_current_month
                    submittal.save()
                    return HttpResponseRedirect(reverse('submittal:submittal_detail', kwargs={'submittal_id': submittal_id}))
                else:
                    leasing_status_prior_month = submittal_prior_month.leasing_status
                    #check that the leasing status is not going from stabilized to leaseup
                    if leasing_status_prior_month == 'stabilized' and leasing_status_current_month == 'leaseup':
                        return render(request, 'submittal/edit_leasing_status.html',{'form': form,
                                                                     'submittal': submittal,
                                                                     'property': property,
                                                                    'input_form_title': input_form_title
                                                                     })
                    #check if the leasing status is going from leaseup to stabilized, and if so,
                    #redirect to a field where they can enter the stabilization date
                    elif leasing_status_prior_month == 'leaseup' and leasing_status_current_month == 'stabilized':
                        submittal.leasing_status = leasing_status_current_month
                        submittal.save()
                        return HttpResponseRedirect(reverse('submittal:edit_stabilization_date', kwargs={'submittal_id': submittal_id}))
                    #if none of the other conditions met, assume no change and the user can save
                    else:
                        submittal.leasing_status = leasing_status_current_month
                        submittal.save()
                        return HttpResponseRedirect(reverse('submittal:submittal_detail', kwargs={'submittal_id': submittal_id}))
        else:
            form = EditLeasingStatusForm(
                leasing_status_choices=options,
                initial={
                    'leasing_status': submittal.leasing_status,
                }
            )
        return render(request, 'submittal/edit_leasing_status.html',{'form': form,
                                                                     'submittal': submittal,
                                                                     'property': property,
                                                                     'input_form_title': input_form_title,
                                                                     })
@login_required
def EditStabilizationDate(request, submittal_id):
    submittal = Submittal.objects.get(id=submittal_id)
    property_id = submittal.prop_id
    property = Property.objects.get(id=property_id)
    date_choices = DateChoices()
    input_form_title = 'Edit Stabilization Date'
    authorized_user = CheckAuthorization(request, property_id)
    if authorized_user == True:
        if request.method == 'POST':
            form = EnterStabilizationDateForm(
                data=request.POST,
                year_choices=date_choices['year_choices'],
                month_choices=date_choices['month_choices'],
                day_choices=date_choices['day_choices'],
            )
            if form.is_valid():
                data = form.cleaned_data
                year = data['stabilization_year']
                month = data['stabilization_month']
                day = data['stabilization_day']
                date_check = CheckDates(year=year, month=month, day=day)
                stabilization_date_check = StabilizationOpeningDateCheck(property_id=property_id,
                                                                         stabilization_year=year,
                                                                         stabilization_month=month,

submittal/templates/submittal/edit_input_form.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_dollar_amount' submittal.id input_type %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

submittal/templates/submittal/edit_leasing_status.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_leasing_status' submittal.id %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save Leasing Status" />
</form>

{% endblock %}

submittal/templates/submittal/edit_opening_date.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_opening_date' submittal.id %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save Opening Date" />
</form>

{% endblock %}

submittal/templates/submittal/edit_quantity_form.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_quantity_amount' submittal.id input_type %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

submittal/templates/submittal/edit_rate_form.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_rate' submittal.id input_type %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

submittal/templates/submittal/edit_stabilization_date.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_stabilization_date' submittal.id %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save Stabilization Date" />
</form>

{% endblock %}

submittal/templates/submittal/edit_yes_no_form.html
{% extends 'Project/base.html' %}

{% block content %}

{% include 'Project/submittal_input_base.html' %}

<form action="{% url 'submittal:edit_yes_no' submittal.id input_type %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>

{% endblock %}

submittal/templates/submittal/submittal_detail.html
{% extends 'Project/base.html' %}

{% block content %}

<p>Property: <a href="{% url 'property:property_detail' property.id %}">{{ property.prop_name }}</a></p>
<p>Submittal: {{ submittal.submittal_month }}/{{ submittal.submittal_year }}</p>
<table>
    <tr>
        <td>Leasing Status:</td>
        <td>{{ submittal.leasing_status }}</td>
        {% if submittal_status == 'open' %}
            <td><a href="{% url 'submittal:edit_leasing_status' submittal.id %}">Edit</a></td>
        {% endif %}
    </tr>
    <tr><td>---</td></tr>
    {% if leasing_status_confirmed == 'Yes' %}
        <tr>
            <td>Opening Date: </td>
            <td>{{ property.date_opening }}</td>
            <td><a href="{% url 'submittal:edit_opening_date' submittal.id %}">Edit</a></td>
        </tr>
        {% if open_date_complete == 'complete' %}
            <tr>
                <td>Stabilization Date:</td>
                <td>{{ property.date_stabilization }}</td>
                <td><a href="{% url 'submittal:edit_stabilization_date' submittal.id %}">Edit</a></td>
            </tr>
            {% if stabilization_date_complete == 'complete' %}
                <tr>
                    <td>End of Period Occupancy Rate (%):</td>
                    <td>{{ submittal.occupancy_rate }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_rate' submittal.id 'occupancy_rate' %}">Edit</a></td>
                    {% endif %}
                </tr>
                <tr><td>---</td></tr>
                <tr>
                    <td>Operating Revenue (Monthly):</td>
                </tr>
                <tr>
                    <td>Budget ($):</td>
                    <td>{{ submittal.op_rev_month_budget }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'op_rev_month_budget' %}">Edit</a></td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Actual ($):</td>
                    <td>{{ submittal.op_rev_month_actual }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'op_rev_month_actual' %}">Edit</a></td>
                    {% endif %}
                </tr>
                {% if fiscal_half_end == 'Yes' %}
                    <tr><td>---</td></tr>
                    <tr>
                        <td>Net Operating Income (Semi-Annual)</td>
                    </tr>
                    <tr>
                        <td>Budget ($):</td>
                        <td>{{ submittal.noi_semi_ann_budget }}</td>
                        {% if submittal_status == 'open' %}
                            <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'noi_semi_ann_budget' %}">Edit</a></td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Actual ($):</td>
                        <td>{{ submittal.noi_semi_ann_actual }}</td>
                        {% if submittal_status == 'open' %}
                            <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'noi_semi_ann_actual' %}">Edit</a></td>
                        {% endif %}
                    </tr>
                {% endif %}
                {% if fiscal_qtr_end == 'Yes' %}
                    <tr><td>---</td></tr>
                    <tr>
                        <td>Total Operating Revenue (Quarter-End)</td>
                    </tr>
                    <tr>
                        <td>Budget ($):</td>
                        <td>{{ submittal.op_rev_qtr_budget }}</td>
                        {% if submittal_status == 'open' %}
                            <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'op_rev_qtr_budget' %}">Edit</a></td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Actual ($):</td>
                        <td>{{ submittal.op_rev_qtr_actual }}</td>
                        {% if submittal_status == 'open' %}
                            <td><a href="{% url 'submittal:edit_dollar_amount' submittal.id 'op_rev_qtr_actual' %}">Edit</a></td>
                        {% endif %}
                    </tr>
                {% endif %}
                <tr><td>---</td></tr>
                <tr>
                    <td>Delinquency Rate (%):</td>
                    <td>{{ submittal.delinquency_rate }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_rate' submittal.id 'delinquency_rate' %}">Edit</a></td>
                    {% endif %}
                </tr>
                <tr><td>---</td></tr>
                <tr>
                    <td>Bad Debt Write-Offs (Yes/No)</td>
                    <td>{{ bad_debt_writeoff }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_yes_no' submittal.id 'bad_debt_writeoffs' %}">Edit</a></td>
                    {% endif %}
                </tr>
                <tr><td>---</td></tr>
                <tr>
                    <td>Lease-Up Override Bonus (Yes/No):</td>
                    <td>{{ lease_up_override }}</td>
                    {% if submittal_status == 'open' %}
                        <td><a href="{% url 'submittal:edit_yes_no' submittal.id 'lease_up_override' %}">Edit</a></td>
                    {% endif %}
                </tr>
            {% endif %}
        {% endif %}
    {% endif %}
</table>

{% if data_points_complete == 'complete' %}
    <p>Employees</p>
    <table style="border: 1px solid black; width: 100%">
        <tr>
            <td>Employee #</td>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Position</td>
            <td>Status</td>
        </tr>
        {% for employee in employees.all %}
            <tr>
                <td>{{ employee.emp_id }}</td>
                <td>{{ employee.emp_name_first }}</td>
                <td>{{ employee.emp_name_last }}</td>
                <td>{{ employee.job_title }}</td>
                <td>{{ employee.emp_status }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% if employee_selections == 'complete' %}
    <p>Submit</p>
{% endif %}

{% endblock %}