Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.debug import default_urlconf

urlpatterns = [
    url(r'^$', default_urlconf),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^property/', include('property.urls', namespace="property")),
    url(r'^user_access/', include('user_access.urls', namespace="user_access")),
    url(r'^submittal/', include('submittal.urls', namespace="submittal")),
    url(r'^submittal_employees/', include('submittal_employees.urls', namespace="submittal_employees")),
]

property/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^property_test/$', views.PropertyTest, name='property_test'),
    url(r'^(?P<property_id>[0-9]+)/$', views.PropertyDetail, name='property_detail'),
    url(r'^', views.PropertyIndex, name='index'),
]

submittal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<submittal_id>[0-9]+)/edit_yes_no/(?P<yes_no_type>\w+)/$', views.EditYesNo, name='edit_yes_no'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_quantity/(?P<quantity_input_type>\w+)/$', views.EditQuantityAmount, name='edit_quantity_amount'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_amount/(?P<dollar_input_type>\w+)/$', views.EditDollarAmount, name='edit_dollar_amount'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_rate/(?P<rate_type>\w+)/$', views.EditRate, name='edit_rate'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_opening_date/$', views.EditOpeningDate, name='edit_opening_date'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_stabilization_date/$', views.EditStabilizationDate, name='edit_stabilization_date'),
    url(r'^(?P<submittal_id>[0-9]+)/edit_leasing_status/$', views.EditLeasingStatus, name='edit_leasing_status'),
    url(r'^(?P<submittal_id>[0-9]+)/$', views.SubmittalDetail, name='submittal_detail')
]

user_access/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login', views.Login, name='login'),
    url(r'^logout', views.Logout, name='logout'),
]

templates/Project/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Bozzuto Bonus</title>
        <style>
            td {color: #00694E; font-family: Arial}
            body {background-color: #CFD4D8}
            h5 {color: #00694E; font-family: Arial}
            h1 {color: black; font-family: Arial}
            p {color: #00694E; font-family: Arial}
        </style>
    </head>
    <body>
        <div>
            <h5><a href="{% url 'user_access:logout' %}" >Log-Out</a></h5>
            <h1><a href="{% url 'property:index' %}">Bozzuto Bonus Form</a></h1>
            {% ifnotequal message '' %}
                <p style="color:red;">{{ message }}</p>
            {% endifnotequal %}
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

templates/Project/submittal_input_base.html
<p>Property: <a href="{% url 'property:property_detail' property.id %}">{{ property.prop_name }}</a></p>
<p>Submittal: <a href="{% url 'submittal:submittal_detail' submittal.id %}">{{ submittal.submittal_month }}/{{ submittal.submittal_year }}</a></p>
<p>{{ input_form_title }}</p>